// <auto-generated />
namespace PlataformaDeVuelos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class añadoValidacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(añadoValidacion));
        
        string IMigrationMetadata.Id
        {
            get { return "202103291423005_añadoValidacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
